### ISSUE TITLE
Database Present in Commit History

### ISSUE THREAD

**Issue by flacey** [CSGY-9223-Group2/lab_one#11]
In commit 7ee6be4e10ee2a49af0e1ca1bb7ee96fe82aaf09, the users SQLite database was added to the commit and pushed into the repo. 
As such, this could allow a malicious actor to try to steal credentials. In downloading the file and simply just viewing the contents in a text editor, there is enough information to gather usernames and password hashes.

While we've currently adopted a model that the database does not persist across deployments, it would be good practice to ensure as a remediation step that any users' bearer tokens are rotated and the file removed from the repo. The rotation ensures that even though the file will still live in commit history, the data present will no longer be valid.

**Comment by szf24** [comment]
This has been resolved: a git ignore has been established but more importantly we've moved from using a sqllite database to an ephemeral database so this is not saved/needed any longer
